
import '@fortawesome/fontawesome-svg-core/styles.css';
import {config} from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false;

import type { Metadata } from "next";
import ".././styles/globals.scss";
import  Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import ProvidersWrapper from "@/components/layout/ProvidersWrapper";
import MenuSidebar from "@/components/layout/menu-sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; 

export const dynamic = 'force-dynamic';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
      <body>
        <ProvidersWrapper>
          <div>
            {children}
            <Footer />
          </div>
        </ProvidersWrapper>
      </body>
    </html>
  );
}
